Category.create(categoryname: "Automobiles")
Category.create(categoryname: "Computer")
Category.create(categoryname: "LostConnections")
Post.create(title: "Ugly Fiat", description: "Ugly color", category_id: 1)
Post.create(title: "Ford Mustand 1969", description: "Black", category_id: 1)
Post.create(title: "Scion FRS", description: "Blue", category_id: 1)
Post.create(title: "Apple MBP Retina 15.4", description: "Silver 568GB SSD", category_id: 2)
Post.create(title: "Apple MBA  11.2", description: "Silver 128GB SSD", category_id: 2)
Post.create(title: "Apple MBP  13.1", description: "Silver 500GB AAMD", category_id: 2)
Post.create(title: "Guy I met at Burning man", description: "You had a guerilla suit on, with a king's crown that was titled: bananas" , category_id: 3)
Post.create(title: "Girl I met at a coffee shop", description: "You smelled like pesto potatoes with truffle oil, and i loved it" , category_id: 3)
Post.create(title: "Hot momma on the Dance FLoor", description: "I bought you 3 drinks and we danced the night away, but never saw your face, holla at me" , category_id: 3)

